# Generated by Django 5.0.3 on 2024-03-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetable',
            name='CoursePrice',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=10),
            preserve_default=False,
        ),
    ]
