# Generated by Django 5.0.3 on 2024-03-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_coursetable_course_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetable',
            name='Course_Days',
            field=models.TextField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Free', 'Free')], verbose_name='Days'),
        ),
    ]
