# Generated by Django 5.0.3 on 2024-03-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_coursetable_course_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
    ]
