# Generated by Django 5.0.3 on 2024-03-31 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_remove_customer_about_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmenttable',
            old_name='student_id',
            new_name='User_id',
        ),
    ]
